FROM alpine

RUN apk update && apk add s6-networking python3 
RUN adduser mozart -D

EXPOSE 7751
USER mozart
COPY ./answer_piano1.py /home/piano/answer_piano1.py
COPY ./piano1.py /home/piano/piano1.py
CMD s6-tcpserver 0.0.0.0 7751 python3 /home/piano/piano1.py
