FROM alpine

RUN apk update && apk add s6-networking python3 
RUN adduser rachmaninov -D

EXPOSE 7753
USER rachmaninov
COPY ./answer_piano3.py home/piano/answer_piano3.py
COPY ./piano3.py home/piano/piano3.py
CMD s6-tcpserver 0.0.0.0 7753 python3 home/piano/piano3.py
