version: '3.9'
services:

 web:
   build: ./webapp

   ports:
     - 5000:5000

   restart: "on-failure"

   networks:
     - noidea

 bot:
   build: ./bot

   restart: "on-failure"

   depends_on:
     - web

   networks:
     - noidea

networks:
 noidea: